### ISSUE TITLE
Error starting up the service

### ISSUE THREAD

**Issue by rahulvramesh** [Proteusiq/huggingfastapi#2]
PYTHONPATH=huggingfastapi/ uvicorn huggingfastapi.main:app --reload --host 0.0.0.0
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [3515] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/huggingfastapi/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/workspace/huggingfastapi/venv/lib/python3.8/site-packages/uvicorn/main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/workspace/huggingfastapi/venv/lib/python3.8/site-packages/uvicorn/main.py", line 389, in serve
    config.load()
  File "/workspace/huggingfastapi/venv/lib/python3.8/site-packages/uvicorn/config.py", line 288, in load
    self.loaded_app = import_from_string(self.app)
  File "/workspace/huggingfastapi/venv/lib/python3.8/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/workspace/huggingfastapi/venv/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/huggingfastapi/./huggingfastapi/main.py", line 2, in <module>
    from huggingfastapi.api.routes.router import api_router
  File "/workspace/huggingfastapi/./huggingfastapi/api/routes/router.py", line 3, in <module>
    from huggingfastapi.api.routes import heartbeat, prediction
  File "/workspace/huggingfastapi/./huggingfastapi/api/routes/prediction.py", line 7, in <module>
    from huggingfastapi.services.nlp import QAModel
  File "/workspace/huggingfastapi/./huggingfastapi/services/nlp.py", line 4, in <module>
    from transformers import AutoTokenizer
  File "/workspace/huggingfastapi/venv/lib/python3.8/site-packages/transformers/__init__.py", line 626, in <module>
    from .trainer import Trainer
  File "/workspace/huggingfastapi/venv/lib/python3.8/site-packages/transformers/trainer.py", line 69, in <module>
    from .trainer_pt_utils import (
  File "/workspace/huggingfastapi/venv/lib/python3.8/site-packages/transformers/trainer_pt_utils.py", line 40, in <module>
    from torch.optim.lr_scheduler import SAVE_STATE_WARNING
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/workspace/huggingfastapi/venv/lib/python3.8/site-packages/torch/optim/lr_scheduler.py)

**Comment by Proteusiq** [comment]
Interesting 🤔 I will try to reproduce and fix it tomorrow

**Comment by Proteusiq** [comment]
fixed #1  together. The issue was with requirements changes

**Comment by rahulvramesh** [comment]
thanks @Proteusiq will try it out.
